# WEB SCRAPING-ASSIGNMENT4

In [1]:
# calling the required libraries for the entire assignment questions
from bs4 import BeautifulSoup   
import requests
import selenium
import pandas as pd
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
import time
import re
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import ElementClickInterceptedException
from selenium.common.exceptions import ElementNotInteractableException
from selenium.webdriver.support import expected_conditions as EC
import warnings
warnings.filterwarnings("ignore")

# QUESTION 1

In [2]:
# 1. Scrape the details of most viewed videos on YouTube from Wikipedia.
# Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:
# A) Rank
# B) Name
# C) Artist
# D) Upload date
# E) Views

web_page = requests.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos") #creating request object
bsoup=BeautifulSoup(web_page.content)  # using beautiful soup to extract the data. #creating soup object
rows = bsoup.find_all('tr')  # Extract all the rows with 'tr' tag
contents = []
for i in rows:
    columns=i.find_all('td')  # Extract all the cells with 'td' tag from each row and store in a list
    columns=[x.text.strip() for x in columns] # Scrapping each element from the list
    contents.append(columns) # Appending list "contents" with each scrapped element
# creating the dataframe with contents
df1 = pd.DataFrame(data=contents) # dataframe with "contents"
df2 = df1.iloc[2:32 ,0:5]  # extracting the required data per question
# Defining required column names
df2.columns =['Rank','Video Name', 'Uploader', 'Views (billions)','Upload Date']
# Displaying the dataframe
df2

,Rank,Video Name,Uploader,Views (billions),Upload Date
2,1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,11.98,"June 17, 2016"
3,2.,"""Despacito""[7]",Luis Fonsi,8.04,"January 12, 2017"
4,3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,6.56,"October 8, 2016"
5,4.,"""Bath Song""[15]",Cocomelon – Nursery Rhymes,5.88,"May 2, 2018"
6,5.,"""Shape of You""[16]",Ed Sheeran,5.87,"January 30, 2017"
7,6.,"""See You Again""[18]",Wiz Khalifa,5.73,"April 6, 2015"
8,7.,"""Phonics Song with Two Words""[23]",ChuChu TV,5.07,"March 6, 2014"
9,8.,"""Uptown Funk""[24]",Mark Ronson,4.78,"November 19, 2014"
10,9.,"""Learning Colors – Colorful Eggs on a Farm""[25]",Miroshka TV,4.76,"February 27, 2018"
11,10.,"""Wheels on the Bus""[26]",Cocomelon – Nursery Rhymes,4.76,"May 24, 2018"
12,11.,"""Gangnam Style""[27]",Psy,4.63,"July 15, 2012"
13,12.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,4.52,"January 31, 2012"
14,13.,"""Dame Tu Cosita""[33]",El Chombo,4.17,"April 5, 2018"
15,14.,"""Sugar""[34]",Maroon 5,3.80,"January 14, 2015"
16,15.,"""Roar""[35]",Katy Perry,3.70,"September 5, 2013"
17,16.,"""Counting Stars""[36]",OneRepublic,3.70,"May 31, 2013"
18,17.,"""Axel F""[37]",Crazy Frog,3.66,"June 16, 2009"
19,18.,"""Sorry""[38]",Justin Bieber,3.61,"October 22, 2015"
20,19.,"""Thinking Out Loud""[39]",Ed Sheeran,3.53,"October 7, 2014"
21,20.,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,3.46,"June 25, 2018"
22,21.,"""Dark Horse""[41]",Katy Perry,3.42,"February 20, 2014"
23,22.,"""Waka Waka (This Time for Africa)""[42]",Shakira,3.39,"June 4, 2010"
24,23.,"""Faded""[43]",Alan Walker,3.38,"December 3, 2015"
25,24.,"""Let Her Go""[44]",Passenger,3.36,"July 25, 2012"
26,25.,"""Girls Like You""[45]",Maroon 5,3.35,"May 31, 2018"
27,26.,"""Perfect""[46]",Ed Sheeran,3.33,"November 9, 2017"
28,27.,"""Bailando""[47]",Enrique Iglesias,3.31,"April 11, 2014"
29,28.,"""Lean On""[48]",Major Lazer,3.30,"March 22, 2015"
30,29.,"""Humpty the train on a fruits ride""[49]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,3.26,"January 26, 2018"
31,30.,"""Lakdi Ki Kathi""[50]",Jingle Toons,3.24,"June 14, 2018"

# QUESTION 2

In [3]:
# 2. Scrape the details team India’s international fixtures from bcci.tv. Url = https://www.bcci.tv/.
# You need to find following details:
# A) Match title (I.e. 1st ODI)
# B) Series
# C) Place
# D) Date
# E) Time
# Note: - From bcci.tv home page you have reach to the international fixture page through code.

# Connect to the driver
driver=webdriver.Chrome(r"chromedriver.exe")

# Opening web page on automated chrome web browser
driver.get("https://www.bcci.tv/")
time.sleep(3)  # 3 seconds sleep

# maximize the window's size
driver.maximize_window()

#delete the cookies  
driver.delete_all_cookies()

# click on "INTERNATIONAL" option
search=driver.find_element(By.XPATH, "/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a")
search.click()
driver.implicitly_wait(5) # seconds

# click on "ALL TEAMS" option
search=driver.find_element(By.XPATH, '//div[@class="col-lg-2 col-md-2 col-sm-12"]//div[@class="customSelecBox"]')
search.click()
driver.implicitly_wait(5) # seconds

# click on "INDIA" option
# search=driver.find_element(By.XPATH, '//div[@class="col-lg-2 col-md-2 col-sm-12"]//div[@class="cSBListItems ng-binding ng-scope"][2]')
search=driver.find_element(By.XPATH, '//div[@class="col-lg-2 col-md-2 col-sm-12"]//div[contains(text(),"india")]')
search.click()
driver.implicitly_wait(5) # seconds

for _ in range(3): # scroll the page for 3 times
    driver.execute_script("window.scrollBy(0,500)") # scroll the page by 500 pixes each time
    time.sleep(2) # wait for 2 seconds to go to next command 

# defining empty list items as required
Match_title=[]
Series=[]
Place=[]
Date=[]
Time=[]

start=0
end=1
for page in range(start,end): # for loop for scrapping 3 pages
    # scrapping Match Title Names
    title=driver.find_elements(By.XPATH, '//span[@class="matchOrderText ng-binding ng-scope"]') # finding all elements of MATCH TITLES
    try:
        for i in title: # for loop with no. of match titles
            Match_title.append(i.text.strip(" ")[:-1]) # appending the match titles to the list
    except NoSuchElementException: # Error handling exception
        Match_title.append("_")  # Use "_" for missing titles
        
    # scrapping Series details
    series_info=driver.find_elements(By.XPATH, '//span[@class="ng-binding"]') 
    try:
        for i in series_info: 
            Series.append(i.text.strip(" ")) 
    except NoSuchElementException: 
        Series.append("_")  
        
    # scrapping Place details
    Place_info=driver.find_elements(By.XPATH, '//div[@class="fix-place ng-binding ng-scope"]') 
    result1=[]
    try:
        for i in Place_info: 
            result1.append(i.text.strip(" "))
            result2=[i.split("-") for i in result1]
            result3 = [item for l in result2 for item in l]
            Place=[i for i in result3 if result3.index(i)%2!=0]
    except NoSuchElementException: 
        Place.append("_") 
        
    # scrapping Date details
    Date_info=driver.find_elements(By.XPATH, '//h5[@class="ng-binding"]') 
    try:
        for i in Date_info: 
            Date.append(i.text.strip(" ")) 
    except NoSuchElementException: 
        Date.append("_")  
        
    # scrapping Time details
    Time_info=driver.find_elements(By.XPATH, '//h5[@class="text-right ng-binding"]') 
    try:
        for i in Time_info: 
            Time.append(i.text.strip(" ")) 
    except NoSuchElementException: 
        Time.append("_") 
        
driver.close()  # closing the driver

# printing lengths of all items    
print(len(Match_title),len(Series),len(Place),len(Date),len(Time))

# creating a data frame with all the information scrapped
df=pd.DataFrame({'Match title':Match_title,'Series':Series,'Place':Place,'Date':Date,'Time':Time})

# displaying dataframe
df

8 8 8 8 8

,Match title,Series,Place,Date,Time
0,1st T20I,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,"Wankhede Stadium, Mumbai",3 JAN 2023,7:00 PM IST
1,2nd T20I,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,"Maharashtra Cricket Association Stadium, Pune",5 JAN 2023,7:00 PM IST
2,3rd T20I,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,"Saurashtra Cricket Association Stadium, Rajkot",7 JAN 2023,7:00 PM IST
3,1st ODI,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,"Barsapara Cricket Stadium, Guwahati",10 JAN 2023,1:30 PM IST
4,2nd ODI,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,"Eden Gardens, Kolkata",12 JAN 2023,1:30 PM IST
5,3rd ODI,SRI LANKA TOUR OF INDIA ODI SERIES 2022-23,"Greenfield International Stadium, Thiruvanant...",15 JAN 2023,1:30 PM IST
6,1st ODI,NEW ZEALAND TOUR OF INDIA ODI SERIES 2022-23,"Rajiv Gandhi International Stadium, Hyderabad",18 JAN 2023,1:30 PM IST
7,2nd ODI,NEW ZEALAND TOUR OF INDIA ODI SERIES 2022-23,Shaheed Veer Narayan Singh International Cric...,21 JAN 2023,1:30 PM IST

# QUESTION 3

In [4]:
# 3. Scrape the details of selenium exception from guru99.com. Url = https://www.guru99.com/
# You need to find following details:
# A) Name
# B) Description
# Note: - From guru99 home page you have to reach to selenium exception handling page through code.

# Connect to the driver
driver=webdriver.Chrome(r"chromedriver.exe")

# Opening web page on automated chrome web browser
driver.get("https://www.guru99.com/")
time.sleep(3)  # 3 seconds sleep

# maximize the window's size
driver.maximize_window()

#delete the cookies  
driver.delete_all_cookies()

# click on "Selenium" option
search=driver.find_element(By.XPATH, '//ul[@class="menu1"]/li//a[@title="Selenium"]')
search.click()
driver.implicitly_wait(5) # seconds

for _ in range(3): # scroll the page for 3 times
    driver.execute_script("window.scrollBy(0,1000)") # scroll the page by 1000 pixes each time
    time.sleep(1) # wait for 1 second to go to next command 
    
# click on "Selenium Exception" option
Selenium=driver.find_element(By.XPATH, '//td[@class="responsivetable"]//a[@title="Selenium Exception Handling (Common Exceptions List)"]').click()
driver.implicitly_wait(3) # seconds

# click on "Selenium Tutorial" option
Selenium=driver.find_element(By.XPATH, '//div[@class="entry-content-wrap"]/div/p')
driver.implicitly_wait(3) # seconds

# defining empty list items as required
Name=[]
Description=[]

# scrapping Names
Name_info=driver.find_elements(By.XPATH, '//div[@class="entry-content-wrap"]/div/p') # finding all elements of Exception Handling
try:
    for i in Name_info: 
        result1.append(i.text.strip(" ")) # appending the exceptions information to the list
        result2=[i.split(":") for i in result1]
        result3 = [item for l in result2 for item in l]
        Description=[i for i in result3[8:90] if result3.index(i)%2!=0] # appending exceptions descritions
        Name=[i.split(".")[1] for i in result3[7:89] if result3.index(i)%2==0] # appending exceptions names
except NoSuchElementException: # Error handling exception
    print("Error")
    
driver.close()  # closing the driver
    
# printing lengths of all items    
print(len(Name),len(Description))

# creating a data frame with all the information scrapped
df=pd.DataFrame({'Name':Name,'Description':Description})

#Displaying the dataframe
df

41 41

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when a...
1,ElementNotSelectableException,This Selenium exception occurs when an elemen...
2,NoSuchElementException,This Exception occurs if an element could not...
3,NoSuchFrameException,This Exception occurs if the frame target to ...
4,NoAlertPresentException,This Exception occurs when you switch to no p...
5,NoSuchWindowException,This Exception occurs if the window target to...
6,StaleElementReferenceException,This Selenium exception occurs happens when t...
7,SessionNotFoundException,The WebDriver is acting after you quit the br...
8,TimeoutException,Thrown when there is not enough time for a co...
9,WebDriverException,This Exception takes place when the WebDriver...
10,ConnectionClosedException,This type of Exception takes place when there...
11,ElementClickInterceptedException,The command may not be completed as the eleme...
12,ElementNotInteractableException,This Selenium exception is thrown when any el...
13,ErrorInResponseException,This happens while interacting with the Firef...
14,ErrorHandler,Exception is used as a placeholder in case if...
15,ImeActivationFailedException,This expectation will occur when IME engine a...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certi...
18,InvalidArgumentException,It occurs when an argument does not belong to...
19,InvalidCookieDomainException,This happens when you try to add a cookie und...
20,InvalidCoordinatesException,This type of Exception matches an interacting...
21,InvalidElementStateException,It occurs when command can’t be finished when...
22,InvalidSessionIdException,This Exception took place when the given sess...
23,InvalidSwitchToTargetException,This occurs when the frame or window target t...
24,JavascriptException,This issue occurs while executing JavaScript ...
25,JsonException,It occurs when you afford to get the session ...
26,NoSuchAttributeException,This kind of Exception occurs when the attrib...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the ...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching...
30,NotFoundException,This Exception is a subclass of WebDriverExce...
31,RemoteDriverServerException,This Selenium exception is thrown when the se...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be su...
34,UnableToSetCookieException,This occurs if a driver is unable to set a co...
35,UnexpectedTagNameException,Happens if a support class did not get a web ...
36,UnhandledAlertException,This expectation occurs when there is an aler...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an ...
38,UnknownMethodException,This Exception happens when the requested com...
39,UnreachableBrowserException,This Exception occurs only when the browser i...
40,UnsupportedCommandException,This occurs when remote WebDriver doesn’t sen...

# QUESTION 4

In [5]:
# 4. Scrape the details of State-wise GDP of India from statisticstime.com. Url = http://statisticstimes.com/
# You have to find following details:
# A) Rank
# B) State
# C) GSDP(18-19)- at current prices
# D) GSDP(19-20)- at current prices
# E) Share(18-19)
# F) GDP($ billion)
# Note: - From statisticstimes home page you have to reach to economy page through code.

# Connect to the driver
driver=webdriver.Chrome(r"chromedriver.exe")

# Opening web page on automated chrome web browser
driver.get("https://www.statisticstimes.com/")
time.sleep(3)  # 3 seconds sleep

# maximize the window's size
driver.maximize_window()

#delete the cookies  
driver.delete_all_cookies()

# click on "Economy" option
economy=driver.find_element(By.XPATH, '/html/body/div[2]/div[1]/div[2]/div[2]').click()
driver.implicitly_wait(2) # seconds

# click on "India" option
economy=driver.find_element(By.XPATH, '/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]').click()
driver.implicitly_wait(2) # seconds

# click on "GDP of Indian States"
economy=driver.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()
driver.implicitly_wait(2) # seconds

for _ in range(3): # scroll the page for 3 times
    driver.execute_script("window.scrollBy(0,500)") # scroll the page by 500 pixes each time
    time.sleep(1) # wait for 1 second to go to next command
    
# defining empty list items as required
Rank=[]
State=[]
GSDP_18_19_at_current_prices=[]
GSDP_19_20_at_current_prices=[]
Share_18_19=[]
GDP=[]
result1=[]

# scrapping the required details
All_info=driver.find_elements(By.XPATH, '/html/body/div[2]/div[2]/div[5]/div[1]/div/table/tbody/tr/td') # finding all elements of table
try:
    for i in All_info: # for loop with all information
        result1.append(i.text.strip(" ")) # scrapping all details of table
        le=len(result1) # length of list items
        Rank=[result1[i] for i in range(0,le,8)] # scrapping "Rank" details
        State=[result1[i+1] for i in range(0,le-1,8)] # scrapping "State" details
        GSDP_18_19_at_current_prices=[result1[i+3] for i in range(0,le-3,8)] # scrapping "GSDP_18_19_at_current_prices" details
        GSDP_19_20_at_current_prices=[result1[i+2] for i in range(0,le-2,8)] # scrapping "GSDP_19_20_at_current_prices" details
        Share_18_19=[result1[i+4] for i in range(0,le-4,8)] # scrapping "Share_18_19" details
        GDP=[result1[i+5] for i in range(0,le-5,8)] # scrapping "GDP" details
except NoSuchElementException: # Error handling exception
    print("Error")
    
driver.close()  # closing the driver

# printing lengths of all items    
print(len(Rank),len(State),len(GSDP_18_19_at_current_prices),len(GSDP_19_20_at_current_prices),len(Share_18_19),len(GDP))

# creating a data frame with all the information scrapped
df=pd.DataFrame({'Rank':Rank,'State':State,'GSDP 18-19 (Cr INR at Current prices)':GSDP_18_19_at_current_prices,'GSDP 19-20 (Cr INR at Current prices)':GSDP_19_20_at_current_prices,'Share 18-19':Share_18_19,'GDP ($billion)':GDP})

#Displaying the dataframe
df

33 33 33 33 33 33

,Rank,State,GSDP 18-19 (Cr INR at Current prices),GSDP 19-20 (Cr INR at Current prices),Share 18-19,GDP ($billion)
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# QUESTION 5

In [6]:
# 5. Scrape the details of trending repositories on Github.com. Url = https://github.com/
# You have to find the following details:
# A) Repository title
# B) Repository description
# C) Contributors count
# D) Language used
# Note: - From the home page you have to click on the trending option from Explore menu through code.

# Connect to the driver
driver=webdriver.Chrome(r"chromedriver.exe")

# Opening web page on automated chrome web browser
driver.get("https://github.com/")
time.sleep(3)  # 3 seconds sleep

# maximize the window's size
driver.maximize_window()

#delete the cookies  
driver.delete_all_cookies()

# click on "Open Source" option
economy=driver.find_element(By.XPATH, '/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button').click()
driver.implicitly_wait(2) # seconds

# click on "Trending" option
economy=driver.find_element(By.XPATH, '/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a').click()
driver.implicitly_wait(3) # seconds

# scrapping details as required in the question
Repository_title=[]
Repository_description=[]
Contributors_count=[]
Language_used=[]
repository_urls=[]

# scrapping Repository_title
title=driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]') 
try:
    for i in title:
        Repository_title.append(i.text.strip(" ")) 
except NoSuchElementException:
    Repository_title.append("_") 
    
# getting all urls of products displayed on amazon page
url=driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]//a')
for i in url:  # for loop getting the data from urls 
    repository_urls.append(i.get_attribute("href"))  # getting urls through href attribute

for i in repository_urls: # loop for every repository in the list
    driver.get(i)  # Opening each repository 
    driver.implicitly_wait(2) # wait the driver for 1 second
    
    #getting Repository_description details
    try: 
        description=driver.find_element(By.XPATH,'//div[@class="BorderGrid-row hide-sm hide-md"]/div/p')
        Repository_description.append(description.text.strip(" ")) 
    except NoSuchElementException:   # exception handling for Repository description
        Repository_description.append("_")       # replace with "_" for missing details
    
    # getting Contributors_count details
    try: 
        contributors=driver.find_element(By.XPATH,'//h2[@class="h4 mb-3"]//a[contains(text(),"Contributors")]/span')
        Contributors_count.append(contributors.text.strip(" ")) 
    except NoSuchElementException:   
        Contributors_count.append("_")       # replace with "_" for missing details
        
    # getting Language_used details
    try: 
        langauge=driver.find_element(By.XPATH,'//ul[@class="list-style-none"]/li[1]//span[@class="color-fg-default text-bold mr-1"]')
        Language_used.append(langauge.text.strip(" ")) 
    except NoSuchElementException:  
        Language_used.append("_")       # replace with "_" for missing details
        
driver.close()  # closing the driver
        
# printing lengths of all items    
print(len(Repository_title),len(Repository_description),len(Contributors_count),len(Language_used))

# creating a data frame with all the information scrapped
df=pd.DataFrame({'Repository Title':Repository_title,'Repository Description':Repository_description,'Contributors Count':Contributors_count,'Language used':Language_used})

#Displaying the dataframe
df

25 25 25 25

,Repository Title,Repository Description,Contributors Count,Language used
0,LAION-AI / Open-Assistant,_,18,Python
1,SunWeb3Sec / DeFiHackLabs,Reproduce DeFi hacked incidents using Foundry.,22,Solidity
2,ChatGPT-Hackers / ChatGPT-API-server,API server for ChatGPT,4,Go
3,lencx / ChatGPT,"🤖 ChatGPT Desktop Application (Mac, Windows an...",7,Rust
4,skyzh / mini-lsm,A tutorial of building an LSM-Tree storage eng...,2,Rust
5,mouredev / retos-programacion-2023,Ejercicios de código semanales en 2023 de la c...,_,_
6,merbanan / rtl_433,Program to decode radio transmissions from dev...,343,C
7,exaloop / codon,"A high-performance, zero-overhead, extensible ...",6,C++
8,acheong08 / ChatGPT,Lightweight package for interacting with ChatG...,40,Python
9,HavocFramework / Havoc,The Havoc Framework.,8,Go
10,sindresorhus / awesome,😎 Awesome lists about all kinds of interesting...,548,_
11,dreamncn / ParallelsDesktopCrack,_,2,Shell
12,novuhq / novu,The open-source notification infrastructure fo...,231,TypeScript
13,trekhleb / javascript-algorithms,📝 Algorithms and data structures implemented i...,197,JavaScript
14,codecrafters-io / build-your-own-x,Master programming by recreating your favorite...,89,_
15,donnemartin / system-design-primer,Learn how to design large-scale systems. Prep ...,117,Python
16,google / comprehensive-rust,This is the Rust course used by the Android te...,23,Rust
17,RustPython / RustPython,A Python Interpreter written in Rust,301,Rust
18,jlevy / the-art-of-command-line,"Master the command line, in one page",163,_
19,lucidrains / PaLM-rlhf-pytorch,Implementation of RLHF (Reinforcement Learning...,3,Python
20,gin-gonic / gin,Gin is a HTTP web framework written in Go (Gol...,381,Go
21,hehonghui / awesome-english-ebooks,"经济学人(含音频)、纽约客、卫报、连线、大西洋月刊等英语杂志免费下载,支持epub、mobi...",_,CSS
22,sherlock-project / sherlock,🔎 Hunt down social media accounts by username ...,189,Python
23,kamranahmedse / developer-roadmap,"Interactive roadmaps, guides and other educati...",520,TypeScript
24,labmlai / annotated_deep_learning_paper_implem...,🧑‍🏫 59 Implementations/tutorials of deep learn...,16,Jupyter Notebook

# QUESTION 6

In [7]:
# 6. Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/
# You have to find the following details:
# A) Song name
# B) Artist name
# C) Last week rank
# D) Peak rank
# E) Weeks on board
# Note: - From the home page you have to click on the charts option then hot 100-page link through code.

# Connect to the driver
driver=webdriver.Chrome(r"chromedriver.exe")

# Opening web page on automated chrome web browser
driver.get("https://www.billboard.com/")
time.sleep(3)  # 3 seconds sleep

# maximize the window's size
driver.maximize_window()

#delete the cookies  
driver.delete_all_cookies()

# click on "Charts" option
economy=driver.find_element(By.XPATH, '/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a').click()
driver.implicitly_wait(2) # seconds

# click on "BillBoardHot100" 
economy=driver.find_element(By.XPATH, '/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[1]/div/div[2]/span/a').click()
driver.implicitly_wait(5) # seconds

for _ in range(20): # scroll the page for 20 times
    driver.execute_script("window.scrollBy(0,1000)") # scroll the page by 1000 pixes each time
    time.sleep(1) # wait for 3 seconds to go to next command
    
# closing pop-up 
try:
    driver.find_element(By.XPATH, "/html/body/div[1]/div[7]").click()
except (NoSuchElementException,ElementClickInterceptedException) as error:
    print("exception without pop-up")
    driver.switch_to.frame("lightbox-iframe-c9e6c70f-53b6-4149-9c27-80da8cfd6a88")
    driver.implicitly_wait(3) # seconds
    driver.find_element(By.XPATH, "/html/body/div[1]/div[7]").click()
    driver.implicitly_wait(3)
    driver.switch_to.default_content()
    pass

# scrapping details as required in the question
Song_name=[]
Artist_name=[]
Last_week_rank=[]
Peak_rank=[]
Weeks_on_board=[]

# scrapping Song_name
song=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]//h3[@id="title-of-a-story"]') 
try:
    for i in song:
        Song_name.append(i.text.strip(" ")) 
except NoSuchElementException:
    Song_name.append("_")
    
# scrapping Artist_name
artist=driver.find_elements(By.XPATH,"//li[@class='lrv-u-width-100p']//span[contains(@class,'c-label  a-no-trucate a-font-primary-s lrv-u-font-size-14@mobile-max u-line-height-normal@mobile-max u-letter-spacing-0021')]") 
try:
    for i in artist:
        Artist_name.append(i.text.strip(" ")) 
except NoSuchElementException:
    Artist_name.append("_")
    
# scrapping Last_week_rank
last_week_rnk=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]//ul//li[4]') 
try:
    result=[]
    for i in last_week_rnk:
        result.append(i.text.strip(" "))
        le=len(result) # length of list items
        Last_week_rank=[result[i] for i in range(0,le,2)] # scrapping "Last week Rank" details
except NoSuchElementException:
    Last_week_rank.append("_")
    
# scrapping Peak_rank
P_Rank=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]//ul//li[5]') 
try:
    result=[]
    for i in P_Rank:
        result.append(i.text.strip(" "))
        le=len(result) # length of list items
        Peak_rank=[result[i] for i in range(0,le,2)] # scrapping "Peak Rank" details
except NoSuchElementException:
    Peak_rank.append("_")
    
# scrapping Weeks_on_board
Weeks_on_chart=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]//ul//li[6]') 
try:
    for i in Weeks_on_chart:
        Weeks_on_board.append(i.text.strip(" ")) 
except NoSuchElementException:
    Weeks_on_board.append("_")
    
driver.close()  # closing the driver
    
# printing lengths of all items    
print(len(Song_name),len(Artist_name),len(Last_week_rank),len(Peak_rank),len(Weeks_on_board))

# creating a data frame with all the information scrapped
df=pd.DataFrame({'Song Name':Song_name,'Artist Name':Artist_name,'Last Week Rank':Last_week_rank,'Peak Rank':Peak_rank,"Weeks on board":Weeks_on_board})

#Displaying the dataframe
df

exception without pop-up
100 100 100 100 100

,Song Name,Artist Name,Last Week Rank,Peak Rank,Weeks on board
0,All I Want For Christmas Is You,Mariah Carey,1,1,57
1,Rockin' Around The Christmas Tree,Brenda Lee,2,2,51
2,Jingle Bell Rock,Bobby Helms,4,3,48
3,A Holly Jolly Christmas,Burl Ives,5,4,31
4,Last Christmas,Wham!,6,5,30
...,...,...,...,...,...
95,Down Home,Jimmie Allen,-,88,5
96,One Thing At A Time,Morgan Wallen,81,37,3
97,Hold Me Closer,Elton John & Britney Spears,89,6,17
98,Far,SZA,61,61,2
99,All Mine,Brent Faiyaz,95,42,20

# QUESTION 7

In [9]:
# 7. Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/
# You have to find the following details:
# A) Name
# B) Designation
# C) Company
# D) Skills they hire for
# E) Location
# Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

# Connect to the driver
driver=webdriver.Chrome(r"chromedriver.exe")

# Opening web page on automated chrome web browser
driver.get("https://www.naukri.com/hr-recruiters-consultants")
time.sleep(3)  # 3 seconds sleep

# maximize the window's size
driver.maximize_window()

#delete the cookies  
driver.delete_all_cookies()

# click on "Search" location and send required keys
search=driver.find_element(By.XPATH,'//div[@class="inpWrap"]/input[@class="sugInp"]') # Finding Search location
search.click() # Clikcing on Search location
search.send_keys("Data Science") # Sending "Data Science" in search location
time.sleep(2) # wait for 5 seconds to go to next line of code

# click on "Search" button
search=driver.find_element(By.XPATH, '/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button').click()
driver.implicitly_wait(2) # seconds

for _ in range(20): # scroll the page for 20 times
    driver.execute_script("window.scrollBy(0,1000)") # scroll the page by 1000 pixes each time
    time.sleep(1) # wait for 1 second to go to next command 

# defining empty list items as required
Name=[]
Designation=[]
Company=[]
Skills_they_hire_for=[]
Location=[]

start=0
end=1
for page in range(start,end): # for loop for scrapping 1 page
    
    # scrapping Match Names
    name_info=driver.find_elements(By.XPATH, '//p[@class="highlightable"]/a/span') # finding all elements of Names
    try:
        for i in name_info: # for loop with no. of names
            Name.append(i.text.strip(" ")) # appending names to the list
    except NoSuchElementException: # Error handling exception
        Name.append("_")  # Use "_" for missing names
        
    # scrapping Designation
    Designation_info=driver.find_elements(By.XPATH, '//p[@class="highlightable"]//span[@class="ellipsis clr"]') 
    try:
        for i in Designation_info: 
            Designation.append(i.text.strip(" ")) 
    except NoSuchElementException: 
        Designation.append("_") 
        
    # scrapping Company
    Company_info=driver.find_elements(By.XPATH, '//p[@class="highlightable"]/a[2]') 
    try:
        for i in Company_info: 
            Company.append(i.text.strip(" ")) 
    except NoSuchElementException: 
        Company.append("_")
        
    # scrapping Skills_they_hire_for
    Skills_info=driver.find_elements(By.XPATH, '//div[@class="hireSec highlightable"]') 
    try:
        for i in Skills_info: 
            Skills_they_hire_for.append(i.text.strip(" ")) 
    except NoSuchElementException: 
        Skills_they_hire_for.append("_")
        
    # scrapping Location
    Location_info=driver.find_elements(By.XPATH, '//p[@class="highlightable"]/span[2]//small[@class="ellipsis"]') 
    try:
        for i in Location_info: 
            Location.append(i.text.strip(" ")) 
    except NoSuchElementException: 
        Location.append("_")

driver.close()  # closing the driver

# creating a data frame with all the information scrapped
df=pd.DataFrame({'Name':Name,'Designation':Designation,'Company':Company,'Skills/Roles I hire for :':Skills_they_hire_for})

# displaying dataframe
df

,Name,Designation,Company,Skills/Roles I hire for :
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof..."
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration..."
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine..."
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We..."
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec..."
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana..."
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu..."
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres..."
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage..."
10,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++..."
11,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ..."
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele..."
13,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm..."
14,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics"
15,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET..."
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science"
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin..."
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B..."
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re..."
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar..."
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning..."
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee..."
24,Deeparchi Sharma,Company Recruiter,ZIGRAM,"Research, Digital Marketing, Analytics, Softwa..."
25,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc..."
26,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana..."
27,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine..."
28,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product..."
29,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw..."
30,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne..."
31,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software..."
32,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ..."
33,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading..."
34,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S..."
35,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti..."
36,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat..."
37,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ..."
38,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private..."
39,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering"
40,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark..."
41,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary"
42,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim..."
43,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B..."
44,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs"
45,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni..."
46,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute..."
47,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum..."
48,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,..."
49,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage..."

# QUESTION 8

In [10]:
# 8. Scrape the details of Highest selling novels.
# Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare
# You have to find the following details:
# A) Book name
# B) Author name
# C) Volumes sold
# D) Publisher
# E) Genre

web_page = requests.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare") #creating request object
bsoup=BeautifulSoup(web_page.content)  # using beautiful soup to extract the data. #creating soup object
rows = bsoup.find_all('tr')  # Extract all the rows with 'tr' tag
contents = []
for i in rows:
    columns=i.find_all('td')  # Extract all the cells with 'td' tag from each row and store in a list
    columns=[x.text.strip() for x in columns] # Scrapping each element from list
    contents.append(columns) # Appending list "contents" with each scrapped element
# creating the dataframe with contents
df1 = pd.DataFrame(data=contents) # dataframe with "contents"
df2 = df1.iloc[2:102 ,0:6]  # extracting the required data per question
# Defining required column names
df2.columns =['Rank','Title', 'Author', 'Volume Sales','Publisher','Genre']
# Displaying the dataframe
df2

,Rank,Title,Author,Volume Sales,Publisher,Genre
2,1,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
3,2,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
4,3,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
5,4,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
6,5,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...,...
97,96,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
98,97,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
99,98,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
100,99,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
101,100,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# QUESTION 9

In [11]:
# 9. Scrape the details most watched tv series of all time from imdb.com. Url = https://www.imdb.com/list/ls095964455/
# You have to find the following details:
# A) Name
# B) Year span
# C) Genre
# D) Run time
# E) Ratings
# F) Votes

# Connect to the driver
driver=webdriver.Chrome(r"chromedriver.exe")

# Opening web page on automated chrome web browser
driver.get("https://www.imdb.com/list/ls095964455/")
time.sleep(3)  # 3 seconds sleep

# maximize the window's size
driver.maximize_window()

#delete the cookies  
driver.delete_all_cookies()

# scrapping details as required in the question
Name=[]
Year_Span=[]
Genre=[]
Run_Time=[]
Ratings=[]
Votes=[]

# scrapping Name
name_info=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]/a') 
try:
    for i in name_info:
        Name.append(i.text.strip(" ")) 
except NoSuchElementException:
    Name.append("_")

# scrapping Year_Span
Year_Span_info=driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]//span[@class="lister-item-year text-muted unbold"]') 
try:
    for i in Year_Span_info:
        Year_Span.append(i.text.strip(" ")) 
except NoSuchElementException:
    Year_Span.append("_")
    
# scrapping Genre
Genre_info=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[1]/span[5]') 
try:
    for i in Genre_info:
        Genre.append(i.text.strip(" ")) 
except NoSuchElementException:
    Genre.append("_")
    
# scrapping Run_Time
Run_Time_info=driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]/p[1]/span[3]') 
try:
    for i in Run_Time_info:
        Run_Time.append(i.text.strip(" ")) 
except NoSuchElementException:
    Run_Time.append("_")
    
# scrapping Ratings
Ratings_info=driver.find_elements(By.XPATH,'//div[@class="ipl-rating-star small"]/span[2]') 
try:
    for i in Ratings_info:
        Ratings.append(i.text.strip(" ")) 
except NoSuchElementException:
    Ratings.append("_")
    
# scrapping Votes
Votes_info=driver.find_elements(By.XPATH,'//p[@class="text-muted text-small"]//span[@name="nv"]') 
try:
    for i in Votes_info:
        Votes.append(i.text.strip(" ")) 
except NoSuchElementException:
    Votes.append("_")
    
driver.close()  # closing the driver
    
# printing lengths of all items    
print(len(Name),len(Year_Span),len(Genre),len(Run_Time),len(Ratings),len(Votes))

# creating a data frame with all the information scrapped
df=pd.DataFrame({'Name':Name,'Year Span':Year_Span,'Genre':Genre,'Run Time':Run_Time,'Ratings':Ratings,'Votes':Votes})

#Displaying the dataframe
df

100 100 100 100 100 100

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,098,199"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,188,269"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"993,172"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"293,913"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"253,064"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"50,331"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"61,878"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"199,641"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"41,683"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"246,620"

# QUESTION 10

In [12]:
# 10. Details of Datasets from UCI machine learning repositories. Url = https://archive.ics.uci.edu/
# You have to find the following details:
# A) Dataset name
# B) Data type
# C) Task
# D) Attribute type
# E) No of instances
# F) No of attribute
# G) Year
# Note: - from the home page you have to go to the ShowAllDataset page through code.

# Connect to the driver
driver=webdriver.Chrome(r"chromedriver.exe")

# Opening web page on automated chrome web browser
driver.get("https://archive.ics.uci.edu/ml/index.php")
time.sleep(3)  # 3 seconds sleep

# maximize the window's size
driver.maximize_window()

#delete the cookies  
driver.delete_all_cookies()

# click on "View All Sets" option
economy=driver.find_element(By.XPATH, '/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b').click()
driver.implicitly_wait(5) # seconds

# defining empty list items as required
Dataset_name=[]
Data_type=[]
Task=[]
Attribute_type=[]
No_of_instances=[]
No_of_attributes=[]
Year=[]
result1=[]

# scrapping the required details
All_info=driver.find_elements(By.XPATH, '/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td') # finding all elements of table
try:
    for i in All_info: # for loop with all information
        result1.append(i.text.strip(" ")) # scrapping all details of table
        le=len(result1) # length of list items
        Dataset_name=[result1[i] for i in range(0,le,7)] # scrapping "Dataset_name" details
        Data_type=[result1[i+1] for i in range(0,le-1,7)] # scrapping "Data_type" details
        Task=[result1[i+2] for i in range(0,le-2,7)] # scrapping "Default Task" details
        Attribute_type=[result1[i+3] for i in range(0,le-3,7)] # scrapping "Attribute_type" details
        No_of_instances=[result1[i+4] for i in range(0,le-4,7)] # scrapping "Instances" details
        No_of_attributes=[result1[i+5] for i in range(0,le-5,7)] # scrapping "Attributes" details
        Year=[result1[i+6] for i in range(0,le-6,7)] # scrapping "Year" details
except NoSuchElementException: # Error handling exception
    print("Error")
    
driver.close()  # closing the driver

# printing lengths of all items    
print(len(Dataset_name),len(Data_type),len(Task),len(Attribute_type),len(No_of_instances),len(No_of_attributes),len(Year))
le=len(Dataset_name) # length of the list

# creating a data frame with all the information scrapped
df=pd.DataFrame({'Dataset Name':Dataset_name[1:le],'Data Types':Data_type[1:le],'Task':Task[1:le],'Attribute Types':Attribute_type[1:le],'No of Instances':No_of_instances[1:le],'No of Attributes':No_of_attributes[1:le],'Year':Year[1:le]})

#Displaying the dataframe
df

623 623 623 623 623 623 623

,Dataset Name,Data Types,Task,Attribute Types,No of Instances,No of Attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021